# Script to autogenerate a make file based on modules in source folder
# Note: Breaks if a module file has a space in it

program="seavax"
mainModule="src/"$program".bas"

# Workign variables
modules=""
objects=""
cmodules=""
cobjects=""

# Recursively looks up module files and adds to $modules
function rSearch() {
	moduleList=$1"*.bas"
	cmoduleList=$1"*.c"
	pathList=$1"*/"
	
	# Check bas modules
	for module in $moduleList; do
		if [ $module != $mainModule ]; then
			modules="$modules $module"
			object=$(echo "$module" | sed -e 's/src/bin/' -e 's/\.bas/.o/')
			objects="$objects $object"
		fi
	done
	
	# Check C modules
	for cmodule in $cmoduleList; do
		if [ $cmodule != $mainModule ]; then
			if [ $cmodule != $1'*.c' ]; then
				cobject=$(echo "$cmodule" | sed -e 's/src/bin/' -e 's/\.c/.o/')
				cmodules="$cmodules $cmodule"
				cobjects="$cobjects $cobject"
			fi
		fi
	done
	
	# Check sub directories
	for path in $pathList; do
		if [ -d "$path" ]; then
			# Make sure bin directory has matching path
			binPath=$(echo $path | sed 's/src/bin/')
			if [ ! -d "$binPath" ]; then
				mkdir "$binPath"
			fi
			
			# Recurse
			rSearch "$path"
		fi
	done
}



#Make sure bin directory exists first
if [ ! -d "bin" ]; then
	mkdir "bin"
fi

# Make list of modules in source folder
rSearch "src/"


# Set up makefile header
echo "# Autogenerated makefile" > Makefile
echo "" >> Makefile
echo "$program: $mainModule $objects $cobjects" >> Makefile
echo -e "\tfbc $mainModule $objects $cobjects" >> Makefile
echo -e "\tmv \"src/$program\" \"$program\"" >> Makefile
echo "" >> Makefile
echo "" >> Makefile

# Build makefile body
echo "# BASIC modules" >> Makefile
echo "" >> Makefile
for module in $modules; do
	object=$(echo "$module" | sed -e 's/src/bin/' -e 's/\.bas/.o/')
	
	echo "$object: $module" >> Makefile
	echo -e "\tfbc -o $object -c $module" >> Makefile
	echo "" >> Makefile
done

echo "# C modules" >> Makefile
echo "" >> Makefile
for module in $cmodules; do
	object=$(echo "$module" | sed -e 's/src/bin/' -e 's/\.c/.o/')
	
	echo "$object: $module" >> Makefile
	echo -e "\tgcc -o $object -c $module" >> Makefile
	echo "" >> Makefile
done
