# Autogenerated makefile

seavax: src/seavax.bas  bin/API/Chat.o bin/API/Data.o bin/API/HandShake.o bin/API/LoginManagement.o bin/API/MazeGame.o bin/API/MazeGameRoom.o bin/API/ProcessControl.o bin/API/Utilities.o bin/chatroom/ChatMessage.o bin/chatroom/ChatRoom.o bin/cmds/Command.o bin/cmds/CommandEnvironment.o bin/cmds/ParList.o bin/game/GameManager.o bin/game/GameRoom.o bin/game/MazeManager.o bin/player/Account.o bin/player/Client.o bin/player/Player.o bin/server/NetStreamParser.o bin/server/Server.o bin/server/ZRing.o bin/table/Table.o bin/terra/Current.o bin/terra/EnvTiles.o bin/terra/RenderEnv.o bin/terra/SaveRaw.o bin/terra/WorldGen.o  bin/server/test.o
	fbc src/seavax.bas  bin/API/Chat.o bin/API/Data.o bin/API/HandShake.o bin/API/LoginManagement.o bin/API/MazeGame.o bin/API/MazeGameRoom.o bin/API/ProcessControl.o bin/API/Utilities.o bin/chatroom/ChatMessage.o bin/chatroom/ChatRoom.o bin/cmds/Command.o bin/cmds/CommandEnvironment.o bin/cmds/ParList.o bin/game/GameManager.o bin/game/GameRoom.o bin/game/MazeManager.o bin/player/Account.o bin/player/Client.o bin/player/Player.o bin/server/NetStreamParser.o bin/server/Server.o bin/server/ZRing.o bin/table/Table.o bin/terra/Current.o bin/terra/EnvTiles.o bin/terra/RenderEnv.o bin/terra/SaveRaw.o bin/terra/WorldGen.o  bin/server/test.o
	mv "src/seavax" "seavax"


# BASIC modules

bin/API/Chat.o: src/API/Chat.bas
	fbc -o bin/API/Chat.o -c src/API/Chat.bas

bin/API/Data.o: src/API/Data.bas
	fbc -o bin/API/Data.o -c src/API/Data.bas

bin/API/HandShake.o: src/API/HandShake.bas
	fbc -o bin/API/HandShake.o -c src/API/HandShake.bas

bin/API/LoginManagement.o: src/API/LoginManagement.bas
	fbc -o bin/API/LoginManagement.o -c src/API/LoginManagement.bas

bin/API/MazeGame.o: src/API/MazeGame.bas
	fbc -o bin/API/MazeGame.o -c src/API/MazeGame.bas

bin/API/MazeGameRoom.o: src/API/MazeGameRoom.bas
	fbc -o bin/API/MazeGameRoom.o -c src/API/MazeGameRoom.bas

bin/API/ProcessControl.o: src/API/ProcessControl.bas
	fbc -o bin/API/ProcessControl.o -c src/API/ProcessControl.bas

bin/API/Utilities.o: src/API/Utilities.bas
	fbc -o bin/API/Utilities.o -c src/API/Utilities.bas

bin/chatroom/ChatMessage.o: src/chatroom/ChatMessage.bas
	fbc -o bin/chatroom/ChatMessage.o -c src/chatroom/ChatMessage.bas

bin/chatroom/ChatRoom.o: src/chatroom/ChatRoom.bas
	fbc -o bin/chatroom/ChatRoom.o -c src/chatroom/ChatRoom.bas

bin/cmds/Command.o: src/cmds/Command.bas
	fbc -o bin/cmds/Command.o -c src/cmds/Command.bas

bin/cmds/CommandEnvironment.o: src/cmds/CommandEnvironment.bas
	fbc -o bin/cmds/CommandEnvironment.o -c src/cmds/CommandEnvironment.bas

bin/cmds/ParList.o: src/cmds/ParList.bas
	fbc -o bin/cmds/ParList.o -c src/cmds/ParList.bas

bin/game/GameManager.o: src/game/GameManager.bas
	fbc -o bin/game/GameManager.o -c src/game/GameManager.bas

bin/game/GameRoom.o: src/game/GameRoom.bas
	fbc -o bin/game/GameRoom.o -c src/game/GameRoom.bas

bin/game/MazeManager.o: src/game/MazeManager.bas
	fbc -o bin/game/MazeManager.o -c src/game/MazeManager.bas

bin/player/Account.o: src/player/Account.bas
	fbc -o bin/player/Account.o -c src/player/Account.bas

bin/player/Client.o: src/player/Client.bas
	fbc -o bin/player/Client.o -c src/player/Client.bas

bin/player/Player.o: src/player/Player.bas
	fbc -o bin/player/Player.o -c src/player/Player.bas

bin/server/NetStreamParser.o: src/server/NetStreamParser.bas
	fbc -o bin/server/NetStreamParser.o -c src/server/NetStreamParser.bas

bin/server/Server.o: src/server/Server.bas
	fbc -o bin/server/Server.o -c src/server/Server.bas

bin/server/ZRing.o: src/server/ZRing.bas
	fbc -o bin/server/ZRing.o -c src/server/ZRing.bas

bin/table/Table.o: src/table/Table.bas
	fbc -o bin/table/Table.o -c src/table/Table.bas

bin/terra/Current.o: src/terra/Current.bas
	fbc -o bin/terra/Current.o -c src/terra/Current.bas

bin/terra/EnvTiles.o: src/terra/EnvTiles.bas
	fbc -o bin/terra/EnvTiles.o -c src/terra/EnvTiles.bas

bin/terra/RenderEnv.o: src/terra/RenderEnv.bas
	fbc -o bin/terra/RenderEnv.o -c src/terra/RenderEnv.bas

bin/terra/SaveRaw.o: src/terra/SaveRaw.bas
	fbc -o bin/terra/SaveRaw.o -c src/terra/SaveRaw.bas

bin/terra/WorldGen.o: src/terra/WorldGen.bas
	fbc -o bin/terra/WorldGen.o -c src/terra/WorldGen.bas

# C modules

bin/server/test.o: src/server/test.c
	gcc -o bin/server/test.o -c src/server/test.c

